#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: sock-order-mysql-secret
  namespace: sock-order
stringData:
  hostname: #@ data.values.mysql_hostname
  port: #@ data.values.mysql_port
  username: #@ data.values.mysql_username
  password: #@ data.values.mysql_password
  database: #@ data.values.mysql_database