#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")
#@ load("/globals.star", "get_image_location", "globals")

#@overlay/match by=overlay.subset({"kind": "PersistentVolumeClaim", "metadata": {"name": "prometheus-server"}})
---
metadata:
  #@ if/end values.monitoring.prometheus_server.pvc.annotations:
  annotations: #@ values.monitoring.prometheus_server.pvc.annotations
spec:
  #@overlay/replace
  accessModes:
    - #@ values.monitoring.prometheus_server.pvc.accessMode
  #@ if/end values.monitoring.prometheus_server.pvc.storage_class:
  storageClassName: #@ values.monitoring.prometheus_server.pvc.storage_class
  resources:
    requests:
      storage: #@ values.monitoring.prometheus_server.pvc.storage
