#@data/values
---
mysql_hostname: sock-shipping-mysql.sock-shipping.svc.cluster.local
mysql_port: "3306"
mysql_username: sockshop
mysql_password: sockshop
mysql_database: sock_shipping
use_external_mysql: False
sock_issuer_url: