#@data/values
---
mysql_hostname: sock-catalog-mysql.sock-catalog.svc.cluster.local
mysql_port: "3306"
mysql_username: sockshop
mysql_password: sockshop
mysql_database: sock_catalog
use_external_mysql: False
sock_issuer_url: